# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 149)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon.fromTheme("max")
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAcceptDrops(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 3, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 3, 2, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout.addWidget(self.comboBox_8, 3, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAcceptDrops(True)
        self.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAcceptDrops(True)
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.pushB_Init2 = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MAX/Martz90-Circle-Plex.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushB_Init2.setIcon(icon)
        self.pushB_Init2.setCheckable(True)
        self.pushB_Init2.setObjectName("pushB_Init2")
        self.gridLayout.addWidget(self.pushB_Init2, 3, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setAcceptDrops(True)
        self.label_1.setAutoFillBackground(True)
        self.label_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setLineWidth(1)
        self.label_1.setMidLineWidth(0)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAcceptDrops(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAcceptDrops(True)
        self.label_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 4, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAcceptDrops(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAcceptDrops(True)
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.pushB_Init12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_Init12.setIcon(icon)
        self.pushB_Init12.setCheckable(True)
        self.pushB_Init12.setChecked(False)
        self.pushB_Init12.setObjectName("pushB_Init12")
        self.gridLayout.addWidget(self.pushB_Init12, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 3, 1, 1, 1)
        self.pushB_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_Connect.setObjectName("pushB_Connect")
        self.gridLayout.addWidget(self.pushB_Connect, 0, 0, 1, 1)
        self.pushB_Restart = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/MAX/close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushB_Restart.setIcon(icon1)
        self.pushB_Restart.setObjectName("pushB_Restart")
        self.gridLayout.addWidget(self.pushB_Restart, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "REMOTE CasparCG"))
        self.label_7.setText(_translate("MainWindow", "Active"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.label_6.setText(_translate("MainWindow", "Active"))
        self.label_5.setText(_translate("MainWindow", "Active"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.pushB_Init2.setText(_translate("MainWindow", "INIT  WALL  9"))
        self.label_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>ToolTip</p></body></html>"))
        self.label_1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Channel 10</p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "Active"))
        self.label_2.setText(_translate("MainWindow", "Active"))
        self.label_8.setText(_translate("MainWindow", "Active"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.label_4.setText(_translate("MainWindow", "Active"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.label_3.setText(_translate("MainWindow", "Active"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.pushB_Init12.setText(_translate("MainWindow", "INIT WALL 12"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "SDI 1"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "SDI 2"))
        self.pushB_Connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushB_Restart.setText(_translate("MainWindow", "RESTART"))
